### ISSUE TITLE
Libv8.a

### ISSUE THREAD

**Issue by nihalkenkre** [cmdr2/v8-android#5]
Hello.

Would it be possible to compile a v8 binary for android on a Windows machine using mingw ? 

How did you generate the v8 library.

Thank you
Nihal Kenkre.

**Comment by cmdr2** [comment]
Hi Nihal, as you may have seen, the steps I followed for Linux are: https://github.com/cmdr2/v8-android#for-compiling-v8

I haven't tried compiling v8 on Windows, but maybe cygwin could help? Otherwise, these articles seem like potential approaches:
* https://medium.com/angular-in-depth/how-to-build-v8-on-windows-and-not-go-mad-6347c69aacd4
* https://chromium.googlesource.com/external/github.com/v8/v8.wiki/+/c62669e6c70cc82c55ced64faf44804bd28f33d5/Building-with-Gyp.md#prerequisites

Failing that, creating a Linux virtual machine (like I did on my Mac) and following the usual steps is an option.

If you don't need to compile, you can get a recently compiled v8 binary at https://github.com/godmodelabs/ejecta-v8

I hope that helps!

Cheers
~cmdr2

**Comment by nihalkenkre** [comment]
Thank you for the information... Cheers
